apiversion: apps/v1
hpa_apiversion: autoscaling/v1
service_apiversion: v1
app_backend_name: sag-backend-app
app_frontend_name: sag-frontend-app
backend_labels:
  type: back-end
frontend_labels:
  type: front-end
grafana_labels:
  app.kubernetes.io/instance: grafana
prometheus_labels:
  app: prometheus
backend_svc_name: express-app
frontend_svc_name: angular-app
frontend_cont_port: 80 
backend_cont_port: 3000  
frontend_imageTag: suryaprasaath/sag-frontend-app:1.2
backend_imageTag: suryaprasaath/sag-backend-app:1.0
scale_minreplicas: 1
scale_maxreplicas: 3
cpu_utilization_limit: 40
req_cpu: "500m"
req_mem: 500Mi
limit_cpu: 1
limit_mem: 1Gi
scalepod_value: 1
scalepercent_value: 10
scale_periodsecond: 120
port: 3000
nodeport: 30004
secretFile: dbsecretfile
replicaCount: 1
svc_type: LoadBalancer
grafana: grafana
grafana_port: 4000
grafana_target_port: 80
prometheus: prometheus
prometheus_port: 9090
prometheus_target_port: 9090
